
server:
  port: 8888

#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/hm?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    cache=false:
    prefix: classpath:/templates/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix:  .html
    encoding: UTF-8
    #content-type: text/html
    mode: HTML5
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
#    redis:
#        database: 3
#        host: 127.0.0.1
#        port: 6379
#  password: ENC(InC5Jf51Km/w1hMzik2ej83hZqHAg+bU)
#        timeout: 6000
#        jedis:
#            pool:
#                max-active: 200
#                max-idle: 100
#                max-wait: 1000
#                min-idle: 50



mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#showSql
logging:
  level:
    com:
      example:
        mapper : debug






